### ISSUE TITLE
Linear Line of Sight hangs on to outdated attachments

### ISSUE THREAD

**Issue by dfoll** [Esri/military-tools-geoprocessing-toolbox#188]
### Tasks to be done:  16 May 2018
- [x] verify this is still an issue - Completed by @dfoll and @kgonzago
- [ ] Possible Development work for issue if not able to be verified
- [ ] create an automated test
- [ ] verify automated checklist test
- [ ] Create a manual checklist test
- [ ] Verify  a manual checklist test
- [ ] Update CMS
- [ ] Verify CMS 
------------------------------------------------------------------------------

## Expected Behavior
Linear Line of Sight generates profile graph attachments for each row in the output los table. This is done through a join to an attachment table. Each time you run the tool, previous profile graphs should be removed from the attachment table.

## Current Behavior
There is an issue already logged, where row1 of the output los table is joined to all rows in the attachment table that start with a "1". This is a separate issue. It was noticed that the graphs in the attachment table are not overwritten if they do not need to be. For example if the tool is run with 15 observer-target lines are drawn, then 15 graphs are generated and placed in the attachment table. If the tool is run again, and only 12 observer-target lines are drawn, only the first 12 attachments are overwritten, and attachments for lines 13, 14, and 15 remain and are still attached to row1 of the output los. 

## Possible Solution
I tried testing to see what would happen if i renamed the outputs when i ran the tool...Still extraneous attachments, this seems to point to that even when new feature classes are generated, they are creating a copy of the existing attachment table for the new outputs and working from that, then overwriting existing results, instead of creating a brand new relationship and attachment table for the new output.. What probably needs to happen to fix this is that each time the tool is run we should check the attachment table and blow away all rows in the attachment table.

## Steps to Reproduce (for bugs)

1. Run linear line of sight with atleast 6 observers and atleast 4 targets
2. Note that row one of the output los have 11 attachments
3. Run linear line of sight with exactly 4 observers and 4 targets
4. The results from step 3 should yield only 16 profile graphs
5. Look at the attachments to row1 of the output los, note that there are 11 attachements numbered 1, and 10-19.

**Comment by dfoll** [comment]
@kgonzago I'm not sure if I erroneously logged this issue, or if unrelated fixes made over time resolved this, but I am not able to reproduce on ArcMap (10.3.1) or ArcGIS Pro (2.1). 
Suggesting removing labels and moving to Done

**Comment by kgonzago** [comment]
I am unable to repro as well. Closing issue.
