### ISSUE TITLE
After running the LLOS GP tool in ArcMap/ArcScene, a runtime termination message appears on closing/exiting ArcMap/ArcScene

### ISSUE THREAD

**Issue by BobBooth** [Esri/military-tools-geoprocessing-toolbox#200]
### Tasks to finish: 
- [x] Review pull request for checklist test for issue 200 -df
https://github.com/ArcGIS/solutions-defense-test-catalog/pull/137

- [x] Review pull request for changes made in the script -df
https://github.com/Esri/military-tools-geoprocessing-toolbox/pull/318

- [x] Verify from Military Tools Build loaction

----------------------------------------
I used the LLOS GP tool on the MOLE OPLAN DEM (projected to UTM).
It ran, though the symbology of the output was wrong (this may be related to the path issue I reported today #199). The output 3D line follows the terrain, but it monochrome. There is no profile graph available in the popup.
When I close ArcScene afterwards, it terminates with a runtime termination warning. 

## Expected Behavior
Symbology should be correct
Popup should have profile graph
ArcScene should not terminate with runtime error on close.

## Steps to Reproduce (for bugs)
1. Start ArcScene (10.4.1)
2. Add projected UTM DEM
3. Set base height to the DEM, choose attractive color scheme and hillshade effect.
4. Run the LLOS GP tool with one observer and one target across terrain.
5. Get results. Symbology issue. Popup issue.
![image](https://cloud.githubusercontent.com/assets/3801392/21734804/6da9fb20-d433-11e6-91c4-85dfeea7bd49.png)

6. Save Scene document.
7. Close Scene document - get runtime message.
![image](https://cloud.githubusercontent.com/assets/3801392/21734830/94161596-d433-11e6-8b95-68e1c0ac9ae7.png)

## Your Environment

* Version used: 10.4.1
* Environment name and version (e.g. Chrome 39, node.js 5.4): ArcScene
* Operating System and version (desktop or mobile): Desktop

**Comment by BobBooth** [comment]
@mfunk - I'm also seeing this in ArcMap.

**Comment by BobBooth** [comment]
This is still a problem in ArcScene 10.5 with the LLOS GP tool in the current dev branch of the Military Tools.PYT toolbox.
The png profile is being attached (though not displayed easily). The HTML popup has color coded vsisible/not-visible sections. 
ArcScene still exits with error.
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/076582a4-5c32-444a-8624-95e53a81be32)
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/355b5abf-9fe3-4de3-964f-7c4b9258db9b)

**Comment by BobBooth** [comment]
@BobBooth  check again if this still an issue in ArcMap.

**Comment by BobBooth** [comment]
This is a problem in ArcMap 10.5
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/791ff9a7-3398-40ad-a585-f89783da6eac)
Workflow:
1. Add DEM to ArcMap
2. Run LLOS tool
3. Add some Observer and Target points.
4. Set DEM
5. Run tool.
6. Get output.
7. Save the map.
8. Hit the X (Close window button in upper right corner of app) to close ArcMap.
Get error message.

**Comment by BobBooth** [comment]
ArcGIS Pro 2.0.0 does not seem to have this problem.

**Comment by csmoore** [comment]
I didn't fully understand that this crash was just happening on exiting/closing ArcMap or ArcScene so I renamed the title - sounds like one to pass onto core though.  

I guess at least we know that the tbx to pyt change didn't start this problem since it preceded that.

**Comment by BobBooth** [comment]
Was not able to download the daily 2.2 build, due to poor internet connection. Maybe someone else can check this?

**Comment by topowright** [comment]
Looking to have the core team understand this issue further. Tool can be found in the following directory once downloaded locally: 

military Tools.pyt/Visibility/Linear Line Of Sight

Inputs can come from feature sets and any raster should work

**Comment by kgonzago** [comment]
I was able to repro this issue in ArcMap 10.5.1. After further testing, I was able to get a bit more info on the error thrown after closing AM:
![image](https://user-images.githubusercontent.com/6391826/40309724-7a5147aa-5cd8-11e8-90f9-e71bb894e67b.png)

Before throwing this over to development, we need to figure out why this issue happens with our LLOS tool. I will create a simple Python script that replicates the LLOS behavior. Hopefully this new test will shed a bit more light on this issue.

**Comment by BobBooth** [comment]
@kgonzago - I'll bet you that it has to do with the profile graphs, either creating them, or attaching them to the features.

**Comment by kgonzago** [comment]
@BobBooth Confirmed. After more testing, `makeProfileGraph()` on line 1362 is the cultprit.

**Comment by dfoll** [comment]
- reviewed and merged the checklist test - removed G-QA Create (Checklist)

**Comment by kgonzago** [comment]
Verified on ArcMap 10.5 using build 28 from \\<server>\disl\Development\Commercial\Solutions\DefenseSolutions\MilitaryToolsForArcGIS\3.0\28)

**Comment by topowright** [comment]
@kgonzago please add the closing labels for the versions that we are targeted (lowest version of the software. )

**Comment by kgonzago** [comment]
@topowright Thanks and will do.

Testing with Pro 2.1 now.
