### ISSUE TITLE
TableToPolygon - Setting "Line" Parameter Causes Tool to Fail (Pro)

### ISSUE THREAD

**Issue by csmoore** [Esri/military-tools-geoprocessing-toolbox#237]
### Tasks to be done 16 May 2018
- [x] Understand what the failure is based on below comments
- [x] Fix the issue 
- [x] Create checklist test
- [x] Verify checklist test
- [x] Verfiy automated test 
https://github.com/Esri/military-tools-geoprocessing-toolbox/pull/290

-------------------------------

## Expected Behavior

Setting the "Line" parameter to a field should create individual lines/polygons/etc. for each unique field
We should Support strings and ints as inputs. 
## Expected Behavior

Setting the "Line" parameter to a field should create individual lines/polygons/etc. for each unique field
We should Support strings and ints as inputs. 
## Current Behavior

Setting the "Line" parameter causes a python crash in the tool (output below)

## Steps to Reproduce (for bugs)

1. Using test data from: https://github.com/Esri/military-tools-geoprocessing-toolbox/tree/dev/testdata
2. Run TableToPolygon tool, set the Line parameter to field "Name" from the [sample csv](https://github.com/Esri/military-tools-geoprocessing-toolbox/blob/dev/testdata/CSV/TabletoPolygon.csv) 
3. Tool fails

## Your Environment

* ArcGIS Pro 1.4-2.0

```
Running script TableToPolygon...
Adding ID field: Name ...
Converting Polylines to Polygons...
PYTHON ERRORS:
Traceback info:
  File "C:\MyFiles\Work\Github\military-tools-geoprocessing-toolbox\toolboxes\scripts\ConversionUtilities.py", line 135, in polylineToPolygon
    outRows.insertRow([outPoly, inID])

Error Info:
The value type is incompatible with the field type. [Name]
ArcPy ERRORS:
Start Time: Thursday, June 29, 2017 12:28:29 PM
Adding Name to C:\Users\Chris\Documents\ArcGIS\Projects\VizTest\scratch.gdb\outputPolygons...
Succeeded at Thursday, June 29, 2017 12:28:29 PM (Elapsed Time: 0.12 seconds)
Completed script TableToPolygon...
Failed to execute (TableToPolygon).
```

![image](https://user-images.githubusercontent.com/3090809/27699929-f9cba3d2-5cc9-11e7-904f-0de8d697839a.png)

**Comment by BobBooth** [comment]
Here's my doc from encountering this issue:
The Table to Polygon tool is failing when it is run on the repo test data (TableToPolygon_single.csv) if the optional "Line Field" input is set to the Name attribute.  
![image](https://user-images.githubusercontent.com/3801392/39826673-67b43b88-5383-11e8-81e9-822728514e1c.png)

The error message is:
"...
PYTHON ERRORS:
Traceback info:
  File "C:\Users\username\Documents\GitHub\military-tools-geoprocessing-toolbox\toolboxes\scripts\ConversionUtilities.py", line 135, in polylineToPolygon
    outRows.insertRow([outPoly, inID])

Error Info:
The value type is incompatible with the field type. [Name]
..."
 Note, this is not a new problem with the tool in the new Python toolbox, Military Tools.pyt - I am also seeing it with the tool in "Military_Tools_arcmap.tbx"

The table contains this attribute which serves as a group identifier for sets of points that belong together in a given polygon. The result of running the tool on this data should be an output polygon for each of the named areas.
Name field:
![image](https://user-images.githubusercontent.com/3801392/39826231-ff5a6c98-5381-11e8-9599-a9e5916616ba.png)

The **Table to Polyline** tool is working correctly with these inputs, creating a set of line features from the related points, see:
![image](https://user-images.githubusercontent.com/3801392/39826468-c7536a4c-5382-11e8-9d8b-8068589c9bff.png)

The tool runs correctly if it is fed a table with integer group IDs, see:
![image](https://user-images.githubusercontent.com/3801392/39827514-29574b48-5386-11e8-89b7-314414afca53.png)

Tool should create polygons grouped by name field, like the Table to Polyline tool does for lines, given a name field with string values, as well as an ID field with Integer values.

## Steps to Reproduce (for bugs)
Using CSV test data, TableToPolyline_single.cs (https://github.com/Esri/military-tools-geoprocessing-toolbox/blob/dev/testdata/CSV/TableToPolyline_single.csv)

1. Run the Table to Polygon tool.
2. Accept default coordinate format
3. X field should be MGRS_X
4. Y field should be MGRS_Y
5. Name the output polygons
6. Line field should be Name
7. Sort field should be Vsort
8. Accept default Spatial Reference
Tool will fail. 

Fails in both "Military_Tools_arcmap.tbx" and "Military Tools.pyt" (Dev branjch 5/9/18) using ArcMap 10.5

**Comment by BobBooth** [comment]
Fix for this caused a problem with Table to Ellipse. Bob will work on this today.

**Comment by BobBooth** [comment]
I believe that PR https://github.com/Esri/military-tools-geoprocessing-toolbox/pull/319 fixes this.
@topowright  - please review and merge.

**Comment by BobBooth** [comment]
Checklist test created: https://github.com/ArcGIS/solutions-defense-test-catalog/pulls

**Comment by dfoll** [comment]
tested manually from dev branch in pro 2.2 -- removed G-QC Verify (Checklist)
