### ISSUE TITLE
TableToPolyline Incorrectly Re-adds First Group Point

### ISSUE THREAD

**Issue by csmoore** [Esri/military-tools-geoprocessing-toolbox#254]
### Tasks to be done: 

-  [ ] Verify automated test
-  [x] 10.3.1 - Derek build 25
- [x] 10.4.1- @kgonzago - completed using build 35
- [x] 10.5.1 - @kgonzago - completed using build 35
- [x] 10.6 - Lyle
- [x] 10.6.1 - @kgonzago - complete using build 35
- [x] 2.1 - Lyle
- [x] 2.2 - Derek build 25

- [x] Verify CMS doc

------------------------------------------------------- 
When Line Field (group/id) parameter is set, TableToPolyline GP Tool is incorrectly adding the first group point to the line, resulting in a spurious line in the output (see screenshot below).

## Expected Behavior

Polyline to match the points in the table without additional point/line at the end..

## Current Behavior

Polyline adds the first point of  the group to the end of the geometry (like it is trying to close a polygon) resulting in a spurious/incorrect line in the output.

## Steps to Reproduce (for bugs)

1. Run tool with test data from repo - testdata\CSV\TableToPolyline.csv
2. Set Line Field to "Group_" from the table
3. Note results similar to screenshot below, last point should not be present in geometry & line from first point to end point should not be present. 

## Your Environment

* Version used: ArcMap 10.4.1 / latest dev branch from repo

![image](https://user-images.githubusercontent.com/3090809/32333344-0c1d1b18-bfbe-11e7-97fb-5861c8fbaf60.png)

**Comment by kgonzago** [comment]
Fix applied and in this [PR](https://github.com/Esri/military-tools-geoprocessing-toolbox/pull/292)

**Comment by dfoll** [comment]
added G-Doc (CMS) and G-Doc (Website) because I believe the issue should be added to issues addressed
- [ ] What's New Defense page
- [ ] What's new table in Military Tools
- [ ]

**Comment by dfoll** [comment]
I took a look at the fix and it looks like the first and last point of the polyline group are no longer being connected

**Comment by BobBooth** [comment]
I manually checked this as well. Have created a function to test this in the automated tests. Will be submitting PR for it in a couple minutes.

**Comment by ACueva** [comment]
Verified content in CMS.
![2018-05-21_15-24-40](https://user-images.githubusercontent.com/3093940/40333010-305e2e28-5d0b-11e8-93c7-92852b0efda4.jpg)
