### ISSUE TITLE
One toolbox for Military Tools

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/military-tools-geoprocessing-toolbox#262]
### Tasks
Per thoughts of working on this as of 25 Apr I feel like these should be the toolsets in the pyt
- [ ] Update the conversion tools (pyt, test, and automation) - Lyle, Derek
- [ ] Update the Distance and Direction tools - Chris
- [x] Update the Visibility tools - Bob
- [ ] Add the GRG Tools - Chris
- [ ] Update the Utilities (highest points, lowest points, etc) - Bob (these are under Visibility)

#### Dev Tasks

Convert the .tbx tools to .pyt:

Conversion

- [ ] ConvertCoordinates
- [ ] TableTo2PointLine
- [ ] TableToLineOfBearing
- [ ] TableToPoint
- [X] TableToPolygon - #269
- [ ] TableToPolyline
- [ ] TableToEllipse

D&D

- [X] RangeRingsFromInterval - #268
- [X] RangeRingFromMinimumAndMaximum - #268
- [X] RangeRingsFromMinAndMaxTable - #268

Viz

- [X] AddLinearLineOfSightFields - #270 
- [X] AddRadialLineOfSightObserverFields - #270 
- [ ] FindLocalPeaks
- [ ] HighestPoints
- [ ] LinearLineOfSight
- [ ] LowestPoints
- [ ] RadialLineOfSight
- [x] RadialLineOfSightAndRange - #270

GRG

- [X] CreateGRGFromArea - #265
- [X] CreateGRGFromPoint - #265
- [X] CreateReferenceSystemGRGFromArea - #265

___

Add the ability to create grids in desktop products, ArcMap and ArcGIS Pro

GRG tools are maintained currently in this repo, https://github.com/esri/solutions-geoprocessing-toolbox.  

GRG tools are incorporated into the MT GP toolbox

Acceptance Criteria:
Target release: Military Tools 3.0
One toolbox
Tests written and running for tools
Toolbox included in the packaged solution
Tools documented
User documentation complete and published

**Comment by BobBooth** [comment]
I was going to take this one, but I can't seem to assign it to myself.

**Comment by lfunkhouser** [comment]
Moving out of Sprint 6 because this is a bigger conversation and needs to be planned as discussed during a previous Planning meeting. The discussion was focused around GRG is .pyt and Military Tools is not. It is not as easy as just moving it.

**Comment by BobBooth** [comment]
Looks like you can have toolsets in a PYT
https://community.esri.com/thread/75524

**Comment by topowright** [comment]
looking into how we start to move the other tools into a pyt.

**Comment by csmoore** [comment]
I did confirm you could use toolsets:

![image](https://user-images.githubusercontent.com/3090809/39272167-24db727a-48a9-11e8-9240-507f122a9311.png)

**Comment by topowright** [comment]
Spent the day understanding exactly how we can tackle this task. I will work with the team to allow them to understand the work that needs to be done. A quick overview will be taking each tool and adding logic to allow it to behave in a way that allows it to be added to the pyt file. There is a ton of work on this issue that all of us can work on without stepping on each others toes, but we will have to work very closely together to make it happen.

**Comment by csmoore** [comment]
I picked up the "Update the Distance and Direction tools" task above.

Also, this might be a good time to check on the status of the problem of packing .pyt in Pro templates/projects:  https://github.com/ArcGIS/solutions-defense/issues/429 - before we get to the template packaging stage with this toolbox - @topowright @dfoll @ACueva @lfunkhouser

**Comment by topowright** [comment]
I do not see a reason for packaging to be addressed right now based on the thought that we do not package

**Comment by csmoore** [comment]
OK - I was confused looking at the acceptance criteria "Toolbox included in the packaged solution" - but I now see that probably means the MilitaryTools download zip since these tools aren't used in templates

**Comment by BobBooth** [comment]
I will take the Utilities.  I can't edit the issue, for some reason, nor can I assign myself. Some GitHub permissions issue? I am logged in.
@csmoore

**Comment by csmoore** [comment]
@BobBooth - https://github.com/Esri/military-tools-geoprocessing-toolbox/blob/dev/toolboxes/scripts/GRGTools.py#L53 (large files don't show up in [the diff](https://github.com/Esri/military-tools-geoprocessing-toolbox/pull/265/files) )

**Comment by BobBooth** [comment]
So that can be in the PY file it calls, not just in the PYT. Got it.

**Comment by BobBooth** [comment]
Working on creating a VisTools.py file for the PYT to import, to contain the Visibility tools and utilities.

**Comment by BobBooth** [comment]
I have managed to get a PYT to have a Visibility Tools toolset and to include the Add LLOS Fields tool to that toolset.
![image](https://user-images.githubusercontent.com/3801392/39332035-4e537fbe-4974-11e8-9bac-f4cb7b7e5962.png)
Still having some issues getting the tool to run (parameters).

**Comment by topowright** [comment]
When inputting data types I have found this helpful: 
http://pro.arcgis.com/en/pro-app/arcpy/geoprocessing_and_python/defining-parameter-data-types-in-a-python-toolbox.htm

**Comment by csmoore** [comment]
Status for D&D Tools - 

Pyt-ported RangeRingsFromInterval tool is now working as expected ( in [branch](https://github.com/Esri/military-tools-geoprocessing-toolbox/tree/csm/%23262-add-grg) ).

I spent most of the tie figuring out a few things that needed changed to get Feature Set working from the pyt

1. Pyt seems to require the FGDB to be in place, the **lyr** file by itself is not sufficient, it requires the lyr and FGDB
2. In Pro, you have to manually clear the selection or the last point entered is the only point processed (because Pro editing selects the last point)

Also, I noticed that D&D unit tests don't have tests that test the actual GP tools themselves so these tests should also be written

![image](https://user-images.githubusercontent.com/3090809/39364028-74b0d4dc-49fa-11e8-9154-fa8308e32146.png)

![image](https://user-images.githubusercontent.com/3090809/39364721-df54fdc0-49fc-11e8-82c3-f786842c751e.png)

**Comment by BobBooth** [comment]
Working on Add RLOS field.
Tool is not showing up in the Visibility group, and tool name appears blank.
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/97fdb936-dafe-42ac-875c-5c7a7defb508)
I thought that:
        self.label = "Add RLOS Fields"
        self.description = "Adds Observer fields and values to inputFeatures."
        self.category = "Visibility"
would handle that.

**Comment by csmoore** [comment]
The remaining 2 D&D tools were added today in branch: https://github.com/Esri/military-tools-geoprocessing-toolbox/tree/csm/%23262-add-grg

This just needs some more testing and the unit tests written/added for these 3 tools and then a PR can be done for that branch/toolset

![image](https://user-images.githubusercontent.com/3090809/39382828-e4db334e-4a34-11e8-9c25-f1147269c730.png)

**Comment by csmoore** [comment]
@BobBooth - you can also get that behavior if your tool fails to load ( gacks on parameters, validation, etc. ) - if you push your branch I can give it a check

**Comment by topowright** [comment]
I am finishing up the conversion tools. Should have my PR in later tonight.

**Comment by csmoore** [comment]
To provide a clearer picture of the current status, [the original issue](https://github.com/Esri/military-tools-geoprocessing-toolbox/issues/262#issue-299406599) has been updated to list the current state of the .tbx-to-.pyt tool conversion for each tool. It looks like 9 / 21 tools have been converted so we still have some ways to go.

**Comment by lfunkhouser** [comment]
This issue has been converted to an epic and issues for each toolset created: 
* GRG:  https://github.com/Esri/military-tools-geoprocessing-toolbox/issues/276
* Conversion: https://github.com/Esri/military-tools-geoprocessing-toolbox/issues/274
* Distance and Direction: https://github.com/Esri/military-tools-geoprocessing-toolbox/issues/273
* Visibility: https://github.com/Esri/military-tools-geoprocessing-toolbox/issues/275

**Comment by BobBooth** [comment]
Updated What's New and Military Tools home page in GitHub to indicate conversion to PYT format and the addition of the GRG toolset, in PR https://github.com/ArcGIS/arcgis-solutions-website/pull/6431

**Comment by BobBooth** [comment]
Created new GRG toolset page, to match the existing Distance and Direction, Visibility, and Conversion toolset pages (CMS).
