### ISSUE TITLE
Majority of Conversion tools fail at Pro 2.2

### ISSUE THREAD

**Issue by topowright** [Esri/military-tools-geoprocessing-toolbox#263]
### Tasks to be done 16 May 2018

Verify these work at 2.2 daily build at least as of 16 May 2018
- [x] Table to 2 point line
- [x] Table to Ellipse - fails to create shape with any areas. features are created
- [x] Table to Line of Bearing
- [x] Table to Polygon
- [x] Table to Polyline

-----------------------------------------------

While testing the GP toolbox for ArcGIS Pro 2.2 I found that the conversion tools do not run do to a copied layer that is an intermediate layer that cannot be deleted. 
## Expected Behavior
Conversion tools should be able to run

## Current Behavior
Tools cannot run because they cannot delete a intermediate dataset
## Possible Solution
Change writing data to disk to memory

## Steps to Reproduce (for bugs)

1. Open tools list below
2. Run with sample data

## Context
Tools that fail

- Table to 2 point line
- Table to Ellipse
- Table to Line of Bearing
- Table to Polygon
- Table to Polyline

## Your Environment
ArcGIS Pro 2.2

Tool fails due to a error in being able to delete data:

http://pro.arcgis.com/en/pro-app/tool-reference/tool-errors-and-warnings/001001-010000/tool-errors-and-warnings-00576-00600-000600.htm

**Comment by lfunkhouser** [comment]
Removing the V-Pro2.2 label. The version label will be applied when the fix is done and the label added for the version it is fixed in  (more than likely the V-Pro 2.1 and V-MT 3.0 labels)

**Comment by topowright** [comment]
Testing manually on Pro 2.2 daily build I found that the only tool that does not work is the table to ellipse. 

Testing on build 12630

**Comment by topowright** [comment]
@BobBooth is experiencing Table to Ellipsel not working on ArcGIS Pro 2.1 or ArcGIS Pro 2.2

**Comment by BobBooth** [comment]
Except, now it is working fine for me on ArcMap 10.5 and Pro 2.1...
I wonder if this is a GitHub branch sync issue.

**Comment by topowright** [comment]
All of these tools pass in todays build and previous builds. When using meters as input with our test data the shape area shows up as zero because the area is too small based on the output coordinate system.

**Comment by topowright** [comment]
This issue does not have anything to do with the unit test. This is a manual test issue.
