### ISSUE TITLE
Do not add layers to the table to contents for Radial Line of Sight and Range

### ISSUE THREAD

**Issue by topowright** [Esri/military-tools-geoprocessing-toolbox#264]
### Tasks to be done - 17 May 2018
- [x] Stand up Production env for Jenkins - Avi - 4hrs
- [x] MT pipeline - Lyle - 1.5hrs
- [x] Verify MT pipeline from production

- [x] Update the output names to be similar to RLOS based on industry standards - Completed by @kgonzago
- [x] discuss the RLOS tool and the RLOS and Range tool

## Expected Behavior
Layers in the ToC that depict what can be seen and what cannot

## Current Behavior
layers are added to the ToC that do not need to be there

## Steps to Reproduce (for bugs)

1. Open the Radial Line of Sight and Range tool
2. Run the tool with default settings 
3. Review the ToC

## Context
To the end user the results look like a sloppy tool

## Your Environment
ArcGIS Pro 2.2

**Comment by topowright** [comment]
Tested this on 10.6 there is no issue with what is added anymore, but the names that we set are not inline with the others that we use on RLOS. I am going to change those names to better align the two tools.

**Comment by kgonzago** [comment]
@ACueva @topowright What values should replace `wedge` and `fullwedge`?

**Comment by topowright** [comment]
Remove full wedge from output
wedge should now be called fov  (Field of View)
symbology for RLOS and Radial Line of Sight and Range are the same

**Comment by kgonzago** [comment]
Layer names issue resolved and [PR](https://github.com/Esri/military-tools-geoprocessing-toolbox/pull/315) submitted

**Comment by ACueva** [comment]
Verified in Pro 2.2 daily, 2.1, ArcMap 10.6
![2018-06-06_14-49-24](https://user-images.githubusercontent.com/3093940/41069286-180d69b2-69a2-11e8-8d92-2b8a2a6eb18c.jpg)
![2018-06-06_15-31-31](https://user-images.githubusercontent.com/3093940/41069289-19579dce-69a2-11e8-8305-f6a649b35104.jpg)
![2018-06-06_15-51-37](https://user-images.githubusercontent.com/3093940/41069292-1b8eecaa-69a2-11e8-93f8-8e4821607bdc.jpg)
