### ISSUE TITLE
Convert .tbx tools to .pyt: Visibility

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/military-tools-geoprocessing-toolbox#275]
### Tasks to be done: 
- [ ] Look at the unit tests on Pro 2.2 daily build

https://github.com/Esri/military-tools-geoprocessing-toolbox/tree/dev/utils/test
#### Write and Verify Checklist Test: 
- [ ] AddLinearLineOfSightFields  - lyle - written, not verified
- [ ] AddRadialLineOfSightObserverFields  
- [ ] FindLocalPeaks
- [ ] HighestPoints - Derek
- [ ] LinearLineOfSight - Derek - written, not verified because the symbology is not working
- [x] LowestPoints - Bob (Checklist test added, discovered this issue in the process: https://github.com/Esri/military-tools-geoprocessing-toolbox/issues/320   PR submitted for this issue: https://github.com/Esri/military-tools-geoprocessing-toolbox/pull/321)
- [ ] RadialLineOfSight - df - written, not verified
- [ ] RadialLineOfSightAndRange - df - written, not verified
 
#### Verify Automated Tests: 
- [ ] AddLinearLineOfSightFields - The test does not test anything of value (tests in the input field len) 
- [ ] AddRadialLineOfSightObserverFields  
- [ ] FindLocalPeaks
- [ ] HighestPoints
- [ ] LinearLineOfSight
- [x] LowestPoints - Kevin
- [ ] RadialLineOfSight
- [ ] RadialLineOfSightAndRange  

Issue https://github.com/Esri/military-tools-geoprocessing-toolbox/issues/262 has been broken down. The following tools are remaining:

- [X] AddLinearLineOfSightFields - #270
- [X] AddRadialLineOfSightObserverFields - #270
- [X] FindLocalPeaks
- [x] HighestPoints
- [X] LinearLineOfSight
- [x] LowestPoints
- [x] RadialLineOfSight
- [X] RadialLineOfSightAndRange - #270

Acceptance Criteria:
Target release: Military Tools 3.0
Pro 2.1 and Pro 2.2
One toolbox
Tests written and running for tools
Tools documented
User documentation complete and published
Tested
Toolbox included in the .zip

**Comment by BobBooth** [comment]
Editing Python TBX help:
http://desktop.arcgis.com/en/arcmap/10.3/analyze/creating-tools/documenting-a-tool-in-a-python-toolbox.htm

**Comment by csmoore** [comment]
LLOS tool added in branch: https://github.com/Esri/military-tools-geoprocessing-toolbox/tree/csm/%23275-add-llos 

There seems to be a (pre-existing) issue with the order of the parameters and line layers when the tool is run - the sightlines layer seems to block out the los layer:

![image](https://user-images.githubusercontent.com/3090809/39546994-38309c94-4e24-11e8-855e-9f3292154f8c.png)

**Comment by csmoore** [comment]
Development is progressing, however there are 3 things of concern that we may need to take to GP team:

1. How long it takes to open the pyt in ArcMap (15+ seconds to open/expand the .pyt)
    a. Are we doing something wrong or is there anything we can do to speed this up?
2. In Pro, for RLOS, LLOS, I have to select the Create Points tool twice for it to work the first time the tool is opened
    a. First time: Click tool (pencil) and it changes to a pencil briefly then immediately back to navigate (hand icon) tool 
3. When the tool is run from outside Pro, with Pro arcpy (command line or unit test driver) - there is an unhandled/uncatchable exception: 
    a. This exception is thrown when .pyt - toolclass.execute(self, parameters, messages) returns:

```
arcgisscripting.ExecuteError: C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\__init__.py:482: DeprecationWarning: Product and extension licensing is no longer handled with this method.
  return gp.checkOutExtension(extension_code)
C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\__init__.py:538: DeprecationWarning: Product and extension licensing is no longer handled with this method.
```

@ACueva @lfunkhouser @topowright @dfoll @mfunk 

___

Also RLOS added in branch: https://github.com/Esri/military-tools-geoprocessing-toolbox/tree/csm/%23275-add-llos and seems to run as expected (except for items noted above).

![image](https://user-images.githubusercontent.com/3090809/39588013-df8b05b6-4ec8-11e8-8027-49a9f5eb3f03.png)

**Comment by BobBooth** [comment]
Copy/Pasting content into PYT tools help. Started on Add LLOS Fields and Add RLOS Fields.

**Comment by BobBooth** [comment]
Visibility help topics migration completed.

**Comment by BobBooth** [comment]
Updated What's New an Military Tools home page in GitHub to indicate conversion to PYT format, in PR https://github.com/ArcGIS/arcgis-solutions-website/pull/6431

**Comment by ACueva** [comment]
Verified Visibility unit tests are running from within Jenkins:
http://dev0002292:8080/job/GP%20Unit%20tests/job/ArcMap%20Test%20Runner/14/console
Jenkins has been setup to run unit tests against ArcGIS Pro 2.1, ArcGIS Pro 2.2 daily, ArcMap 10.3.1 and ArcMap 10.6.1 Daily.

**Comment by csmoore** [comment]
@ACueva - thanks for reaching out to the GP team - I believe they are asking for a minimal version of the tool that also shows the problem - that is attached below to pass on to them. It just has the LLOS tool parameter, the tool layer/schema dependencies, and no execcute code:

[PythonTeamDebug-MinimalTool.zip](https://github.com/Esri/military-tools-geoprocessing-toolbox/files/1988460/PythonTeamDebug-MinimalTool.zip)

**Comment by ACueva** [comment]
@csmoore @kgonzago 
Running into an issue with our Unit tests running against Pro 2.2 daily build:

```
RESULTS =================================================
Number of tests run: 86
Number succeeded: 85
Number of errors: 0
Number of failures: 1
Number of tests skipped: 0
Percent passing: 98.8
=========================================================

ERROR: 2018-05-11 11:30:13,691 FAILURES ================================================
ERROR: 2018-05-11 11:30:13,691 test_clipRasterToArea (visibility_tests.VisibilityUtilitiesTestCase.VisibilityUtilitiesTestCase)
ERROR: 2018-05-11 11:30:13,691 Traceback (most recent call last):
ERROR: 2018-05-11 11:30:13,691   File "c:\jDev\workspace\GP Unit tests\ArcGIS Pro Test Runner Daily\military-tools-geoprocessing-toolbox\utils\test\visibility_tests\VisibilityUtilitiesTestCase.py", line 198, in test_clipRasterToArea
ERROR: 2018-05-11 11:30:13,692     self.assertEqual(result, "true", "Raster Compare failed: \n %s" % arcpy.GetMessages())
ERROR: 2018-05-11 11:30:13,692 AssertionError: 'false' != 'true'
ERROR: 2018-05-11 11:30:13,692 - false
ERROR: 2018-05-11 11:30:13,692 + true
ERROR: 2018-05-11 11:30:13,692  : Raster Compare failed: 
ERROR: 2018-05-11 11:30:13,692  Start Time: Friday, May 11, 2018 11:20:53 AM
ERROR: 2018-05-11 11:30:13,693 Raster: Extents are different (Base: Top 4072626.278277763, Left 608393.200096963, Right 647971.027435986, Bottom 4033048.45093874, Test: Top 4072650.978558848, Left 608373.9733463809, Right 648008.05914644, Bottom 4033045.021989307).
ERROR: 2018-05-11 11:30:13,693 Raster: Heights are different (Base: 1407, Test: 1408).
ERROR: 2018-05-11 11:30:13,693 Raster: Widths are different (Base: 1407, Test: 1409).
ERROR: 2018-05-11 11:30:13,693 RasterDataset: Extents are different (Base: Top 4072626.278277763, Left 608393.200096963, Right 647971.027435986, Bottom 4033048.45093874, Test: Top 4072650.978558848, Left 608373.9733463809, Right 648008.05914644, Bottom 4033045.021989307).
ERROR: 2018-05-11 11:30:13,693 RasterDataset: Heights are different (Base: 1407, Test: 1408).
ERROR: 2018-05-11 11:30:13,693 RasterDataset: Widths are different (Base: 1407, Test: 1409).
ERROR: 2018-05-11 11:30:13,694 Raster: Bandcollection counts are the same [1].
ERROR: 2018-05-11 11:30:13,694 Raster: PixelTypes are the same [16 bit signed integer].
ERROR: 2018-05-11 11:30:13,694 SpatialReference: Spatial references are the same.
ERROR: 2018-05-11 11:30:13,694 RasterDataset: Bandcollection counts are the same [1].
ERROR: 2018-05-11 11:30:13,694 RasterDataset: PixelTypes are the same [16 bit signed integer].
ERROR: 2018-05-11 11:30:13,694 SpatialReference: Spatial references are the same.
ERROR: 2018-05-11 11:30:13,695 Succeeded at Friday, May 11, 2018 11:20:54 AM (Elapsed Time: 1.72 seconds)
INFO: 2018-05-11 11:30:13,695 END OF TEST =========================================
'One or more tests failed'
Press any key to continue . . . 
Build step 'Execute Windows batch command' marked build as failure
Finished: FAILURE
```
Full results can be found here:
http://StagingServer:8080/job/GP%20Unit%20tests/job/ArcGIS%20Pro%20Test%20Runner%20Daily/30/console

**Comment by csmoore** [comment]
@acueva - This failing test should probably be changed to add some ignore options and tolerances to the raster compare call: https://github.com/Esri/military-tools-geoprocessing-toolbox/blob/dev/utils/test/visibility_tests/VisibilityUtilitiesTestCase.py#L197 - tool options: 
 http://pro.arcgis.com/en/pro-app/tool-reference/data-management/raster-compare.htm

**Comment by ACueva** [comment]
@csmoore Had no luck modifying the tolerances:
My latest attempt of line 197:

```
result = arcpy.RasterCompare_management(expectedOutput, resultClippedRaster, "RASTER_DATASET","","","Heights 3","").getOutput(1)
```

I attempted to run command line from the Jenkins machine:

```
======================================================================
FAIL: test_clipRasterToArea (__main__.VisibilityUtilitiesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\jDev\workspace\GP Unit tests\ArcGIS Pro Test Runner Daily\military-tools-geoprocessing-toolbox\utils\test\visibility_tests\VisibilityUtilitiesTestCase.py", line 198, in test_clipRasterToArea
    self.assertEqual(result, "true", "Raster Compare failed: \n %s" % arcpy.GetMessages())
AssertionError: Raster Compare failed:
 Executing: RasterCompare "C:\jDev\workspace\GP Unit tests\ArcGIS Pro Test Runner Daily\military-tools-geoprocessing-toolbox\testdata\Results.gdb\ExpectedOutputclipRasterToArea" "C:\jDev\workspace\GP Unit tests\ArcGIS Pro Test Runner Daily\military-tools-geoprocessing-toolbox\utils\test\scratch.gdb\resultClippedRaster" RASTER_DATASET # NO_CONTINUE_COMPARE "Heights 3" # # #
Start Time: Fri May 11 17:55:48 2018
Raster: Extents are different (Base: Top 4072626.278277763, Left 608393.200096963, Right 647971.027435986, Bottom 4033048.45093874, Test: Top 4072650.978558848, Left 608373.9733463809, Right 648008.05914644, Bottom 4033045.021989307).
Raster: Heights are different (Base: 1407, Test: 1408).
Raster: Widths are different (Base: 1407, Test: 1409).
RasterDataset: Extents are different (Base: Top 4072626.278277763, Left 608393.200096963, Right 647971.027435986, Bottom 4033048.45093874, Test: Top 4072650.978558848, Left 608373.9733463809, Right 648008.05914644, Bottom 4033045.021989307).
RasterDataset: Heights are different (Base: 1407, Test: 1408).
RasterDataset: Widths are different (Base: 1407, Test: 1409).
Raster: Bandcollection counts are the same [1].
Raster: PixelTypes are the same [16 bit signed integer].
SpatialReference: Spatial references are the same.
RasterDataset: Bandcollection counts are the same [1].
RasterDataset: PixelTypes are the same [16 bit signed integer].
SpatialReference: Spatial references are the same.
Succeeded at Fri May 11 17:55:49 2018 (Elapsed Time: 0.45 seconds)

----------------------------------------------------------------------
Ran 13 tests in 103.417s

FAILED (failures=1)

C:\jDev\workspace\GP Unit tests\ArcGIS Pro Test Runner Daily\military-tools-geoprocessing-toolbox\utils\test\visibility_tests>
```

I'll continue this on Monday unless you find a fix prior.

**Comment by csmoore** [comment]
@ACueva - you may need to modify the tolerances based on the [tool doc](https://github.com/Esri/military-tools-geoprocessing-toolbox/issues/275#issuecomment-388518803) - something like: `"Heights 3 Value" ` or `"All 3 Value"`

**Comment by ACueva** [comment]
PR in to address this failing test: https://github.com/Esri/military-tools-geoprocessing-toolbox/pull/297

**Comment by dfoll** [comment]
Removing G - Doc (CMS) verified that what is in the .pyt matches what is in the Visibility toolset documentation

**Comment by csmoore** [comment]
Looking into the Pro 2.2.daily issues with viz unit tests noted in this PR: 

https://github.com/Esri/military-tools-geoprocessing-toolbox/pull/308#issuecomment-389345178
https://github.com/Esri/military-tools-geoprocessing-toolbox/pull/308#issuecomment-389565088

**Comment by csmoore** [comment]
Addressed 2 of the repeatable failures with the viz unit tests in branch:
https://github.com/Esri/military-tools-geoprocessing-toolbox/tree/csm/%23275-fix-tests-at-pro2.2 

I am now looking into a workaround for the problem of the scratch.gdb becoming corrupted between test runs. The corruption scenario is:

1. In Pro 2.1+
2. Many of our tools call AddField, this creates a schema lock file (.sr.lock) that is not being released until the Pro or the arcpy process exits
3. After a test runs it calls Delete_management to delete the scratch.gdb created
4. Delete_management deletes everything in scratch.gdb folder except the lock file and the scratch.gdb folder remains
5. The next test that runs finds a scratch.gdb folder so doesn't try to (and also can't) create scratch.gdb
6. All of the next tests fail to run because they can't create feature classes in the bad/corrupt/empty scratch.gdb folder

So looking into the logic of the scratch.gdb create/delete to see if this can be improved or this condition can be worked around. But the source of the problem is the locks that should not be being held onto, but this is also a hard problem to reproduce consistently

**Comment by kgonzago** [comment]
Talked with @ACueva and will tackle the visibility unit tests which are failing. Also, I will look into @csmoore's [comment](https://github.com/Esri/military-tools-geoprocessing-toolbox/issues/275#issuecomment-390230978) which will provide guidance on enhancing these unit tests.

**Comment by topowright** [comment]
Currently there are many challenges with our unit tests. Some tests do not test anything meaningful: 
As an example this test only the inputs of a field that does not add any value for our end tool testing.
https://github.com/Esri/military-tools-geoprocessing-toolbox/blob/dev/utils/test/visibility_tests/AddLLOSFieldsTestCase.py

More time needs to be spent to understand what each test is doing and if it is really needed.

**Comment by kgonzago** [comment]
I found the issue with lock files in the `Find Lowest Point` unit tests. Whenever temporary data needs to be deleted, the logic is to iterate through the `deleteme` list in the `finally` block. The logic never checks if the list contains any `NULL`s. That logic for deleting from that list was enhanced and can be found [here](https://github.com/Esri/military-tools-geoprocessing-toolbox/blob/183e1ee820c28832f138dfb684b974fe0a60b30e/toolboxes/scripts/VisibilityUtilities.py#L857). This fix is in this [branch](https://github.com/Esri/military-tools-geoprocessing-toolbox/tree/lw-vis-test-automated)

**Comment by topowright** [comment]
Closing this issue with the idea that we will not be writing any further unit tests at this point. We will open individual issues for tests that will need to be written for each unit test. @lfunkhouser I am closing this issue.

**Comment by lfunkhouser** [comment]
@topowright You are correct that no additional unit tests will be written as part of this issue. The acceptance criteria has changed for this issue, so changing the closing label to "verified" due to the conversion tools are in a .pyt and no longer in .tbx.
