### ISSUE TITLE
Distance and Direction Range Rings are doubling the expected output

### ISSUE THREAD

**Issue by llsjr2** [Esri/military-tools-geoprocessing-toolbox#311]
#### Tasks to be done

- [x] Change the values that get added to the table to be radius not diameter (distance from orgin)
- [x] Create a unit test that tests the values in the field

#### Verify
- [x] The table lables as radius not diameter -Lyle https://github.com/Esri/military-tools-geoprocessing-toolbox/pull/328
- [x] Na unit test that checks the correct attributes in the feature class
Conduct the range ring production the output is double the requested distance.

## Expected Behavior
When the tool is run, the rings should be the distance should be correct in the attribute table for labeling

## Current Behavior
The tool's output is double the distance in the attribute table.
Ran the tool twice with and without the Spatial Reference option.  It did not change the result.  Also ran it with the Map Frame in both GCS and UTM.

![distanceanddirection_range_rings](https://user-images.githubusercontent.com/30242778/40145559-38e6a676-5917-11e8-97a8-ab8a26464e2a.PNG)

## Steps to Reproduce (for bugs)

1. Load a point feature class in Input Center Features
2.Enter the distance of 350 meters
3. Number of Rings of 4
4. Support an output locations
5. Run the tool.
6. Check the results and the attribute table.

## Your Environment
Platform: ArcMap 10.6.1
Projection: GCS WGS1984

**Comment by BobBooth** [comment]
@llsjr2 - I'm seeing the ring geometry being correct, but the distance reported in the table is the diameter of the ring, not the radius of the ring.
![image](https://user-images.githubusercontent.com/3801392/40183474-e91cdfc0-59bb-11e8-9a3a-43772105c884.png)

**Comment by BobBooth** [comment]
I have updated the script in this PR https://github.com/Esri/military-tools-geoprocessing-toolbox/pull/328 to do the field calculation after the final output is created. It was not working on the intermediate table.

**Comment by BobBooth** [comment]
Updated existing (non-cucumber) checklist test with a couple of lines to verify that the range field values are correct, in this PR: https://github.com/ArcGIS/solutions-defense-test-catalog/pull/148

**Comment by BobBooth** [comment]
My thoughts for the automated test are to add something like this around line 318 of the Range Rings from Interval test:

[This is failing at the moment, but, I think it is close]

        #get a list of values in the Range field
        outRingLyr = arcpy.management.MakeFeatureLayer("outRings")
        rangeList = [row[0] for row in arcpy.da.SearchCursor(outRingLyr, "Range")]
        rangeList.sort()
        self.assertTrue(rangeList == [200.0,400.0,600.0,800.0], "Range values not equal to expected values")

**Comment by topowright** [comment]
@BobBooth updated comments in the pull request. The test needs to be written like a cucumber test.

**Comment by BobBooth** [comment]
@topowright - done
@ACueva - please review and merge

**Comment by BobBooth** [comment]
Created update to automated test script to check that Range output values match the inputs given the tool.
https://github.com/Esri/military-tools-geoprocessing-toolbox/pull/329

**Comment by BobBooth** [comment]
This should be working.  
It is on my machine, and the PR got merged.
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/638bb505-34de-42f9-86d4-dcb9e37351b2)
Is the GP toolbox not getting updated right in the Military Tools build process?

**Comment by BobBooth** [comment]
The Dev branch in GitHub has the correct code:
https://github.com/Esri/military-tools-geoprocessing-toolbox/blob/dev/toolboxes/scripts/RangeRingUtils.py
I think this is a problem with the Military Tools packaging process.

**Comment by BobBooth** [comment]
Impeded because I cannot test this from the latest Military Tools build, as the build process is still (as of the latest version, at \Solutions\DefenseSolutions\MilitaryToolsForArcGIS\3.0\27) is not picking up the contents of the dev branch.

**Comment by lfunkhouser** [comment]
This is no longer impeded. The build has been updated to pull from dev.

**Comment by ACueva** [comment]
I tested directly from the MT build.  I can confirm, the changes addressed in this issue show up in the current build.  Build 31
